/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import persistence.BookingDAO;
import java.util.Vector;
import com.prcse.datamodel.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author snowman
 */
public class CancellationJFrame extends javax.swing.JFrame {

    private Vector<Customer> getCancellations() {
         //retrieves the list of cancelled bookings by called getCancellations
        //in the BookingDAO
        BookingDAO dao = new BookingDAO();
        return dao.getCancellations();
    }
    
    private void fillCancellations(Vector<Customer> custlist){
        //This method fills the list of Customer objects, which is returned from calling the
        //above method getCancellations, in the table
         String[] colNames = {"Event" ,"Customer","Created","Created Confirmed","Cancelled","Approved"};
       
         int total = 0;
         for (int i = 0; i<custlist.size() ; i++){
             Customer c = custlist.get(i);
             for (int j=0; j<c.getBookings().size();j++){
                 total++;
             }
         }
         String[][] data = new String[total][6];
         total = 0;
          SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        for (int i = 0; i<custlist.size() ; i++){
             Customer c = custlist.get(i);
            
             for (int j=0; j<c.getBookings().size();j++){
                 
                 data[total][0] = c.getBookings().get(j).getEvent().getName();
                 data[total][1] = c.getForename() + " " + c.getSurname();
                 data[total][2] = sdf.format(c.getBookings().get(j).getCreated());
                 data[total][3] = sdf.format(c.getBookings().get(j).getConfirmed());
                 data[total][4] = sdf.format(c.getBookings().get(j).getCancelled());
                 data[total][5] = sdf.format(c.getBookings().get(j).getCancelConfirmed());
                 total++;
                 
             }
         }
          javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, colNames);
         this.jTable1.setModel(model);
    }
    
    /**
     * Creates new form CancellationJFrame
     */
    //This is the constructor, it is called when the screen is first loaded,
    //it initiates the UI controls by calling initComponents() , then calls
    //fillCancellations to populate the  table with the cancelled bookins,the
    //which takes the results of calling getCancellations() as a parameter.
    public CancellationJFrame() {
        initComponents();
        fillCancellations(getCancellations());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCustomers = new javax.swing.JMenu();
        jMenuArtist = new javax.swing.JMenu();
        jMenuVenue = new javax.swing.JMenu();
        jMenuDate = new javax.swing.JMenu();
        jMenuCancellation = new javax.swing.JMenu();
        jMenuEvents = new javax.swing.JMenu();
        jMenuTour = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Cancellations");
        jLabel2.setToolTipText("");

        jMenuCustomers.setText("Customers");
        jMenuCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCustomersMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCustomers);

        jMenuArtist.setText("Artists");
        jMenuArtist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuArtistMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuArtist);

        jMenuVenue.setText("Venue");
        jMenuVenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuVenueMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuVenue);

        jMenuDate.setText("Dates");
        jMenuDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDateMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuDate);

        jMenuCancellation.setText("Cancellations");
        jMenuCancellation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancellationMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancellation);

        jMenuEvents.setText("Events");
        jMenuEvents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEventsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEvents);

        jMenuTour.setText("Tours");
        jMenuTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuTourMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuTour);

        jMenuExit.setText("Exit");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Cancellations");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCustomersMouseClicked
        // TODO add your handling code here:
        CustomerJFrame  myFrame = new  CustomerJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCustomersMouseClicked

    private void jMenuArtistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuArtistMouseClicked
        // TODO add your handling code here:
        ArtistJFrame  myFrame = new  ArtistJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuArtistMouseClicked

    private void jMenuVenueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuVenueMouseClicked
        // TODO add your handling code here:
        VenueJFrame  myFrame = new  VenueJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jMenuVenueMouseClicked

    private void jMenuDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDateMouseClicked
        // TODO add your handling code here:
        DateJFrame  myFrame = new  DateJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuDateMouseClicked

    private void jMenuEventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEventsMouseClicked
        // TODO add your handling code here:
        EventJFrame  myFrame = new  EventJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuEventsMouseClicked

    private void jMenuTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuTourMouseClicked
        // TODO add your handling code here:
        TourJFrame  myFrame = new  TourJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuTourMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuCancellationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancellationMouseClicked
        // TODO add your handling code here:
        CancellationJFrame  myFrame = new  CancellationJFrame();
        myFrame.setExtendedState(myFrame.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        myFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuCancellationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancellationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancellationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancellationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancellationJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancellationJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuArtist;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancellation;
    private javax.swing.JMenu jMenuCustomers;
    private javax.swing.JMenu jMenuDate;
    private javax.swing.JMenu jMenuEvents;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuTour;
    private javax.swing.JMenu jMenuVenue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
